blank_issues_enabled: false
contact_links:
  - name: Document Redaction Support
    url: https://github.com/deadhand777/doc-redaction/discussions
    about: Please ask and answer questions here
  - name: Document Redaction Documentation
    url: https://deadhand777.github.io/doc-redaction/
    about: Visit our documentation for help
