name: Feature Request
description: Suggest a new feature or enhancement for Document Redaction
title: "[FEATURE] "
labels: ["enhancement", "triage"]
projects:
  - "deadhand777/doc-redaction"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for Document Redaction!
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Describe the problem you're trying to solve. What is currently difficult or impossible to do?
      placeholder: I would like Document Redaction to...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Optional - Describe your proposed solution in detail. How would this feature work?
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Provide specific use cases for the feature. How would people use it?
      placeholder: This would help with...
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Optional - Have you considered alternative approaches? What are their pros and cons?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Include any other context, screenshots, code examples, or references that might help understand the feature request.
